### PR TITLE
Servlet 2 compatibility fix, stuck threads, query strings, and error links

### LINKED ISSUE #20: alert on slow or stuck requests
It'd be helpful if requests that take a very long time trigger some kind of error that show up in rollbar. (It wouldn't be an exception, per se, but we could make a dummy one to show where the execution currently is.)

Perhaps check once a minute or so.

### PR DESCRIPTION
**Pull request by mattdrees**
This is a large PR with a number of features that I've started but haven't finished until now:
 * Servlet 2.x compatibility fix (since SSW uses servlet 2, still)
 * Monitoring for request threads that get stuck (by infinitely blocking IO, infinite loops) (this fixes #20)
 * Recording the query string
 * Generating a rollbar UUID proactively, and using it to put a rollbar link in error pages, logs, and http response headers (the idea is that downstream apps can put this link in their own rollbar reports)

I was motivated to do this because of an OBIEE failure last week that caused all 50 OIBEE answers sessions in one of the Cortex instances to become locked up. I didn't figure out the problem until several hours after it had started. This happened, in a slightly different form, [a year ago](https://docs.google.com/document/d/1x60Ff1FoBfyG9zqdnxvbKe1Qvd6gA81dOygsfxyFyqM/edit#heading=h.xm5s5tnfv72z), as well.

I also had a SSW production problem last week that would have easier to evaluate if person-data capturing was working. This PR makes that possible.

### CODE REVIEW

File: src/main/java/org/cru/redegg/recording/impl/DefaultStuckThreadMonitor.java [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+    {
+        executorService.shutdown();
+        try
+        {
+            executorService.awaitTermination(5, TimeUnit.SECONDS);
+        }
+        catch (InterruptedException e)
+        {
+            Thread.currentThread().interrupt();
+            throw new RuntimeException("interrupted while awaiting termination", e);
```
Comment (frett) [inline src/main/java/org/cru/redegg/recording/impl/DefaultStuckThreadMonitor.java]: Interesting that you are throwing a `RuntimeException` here, I usually just set the interrupt flag and get out of my own code as quickly as possible.

Throwing a RuntimeException means that the caller logic which we don't control won't have a chance to perform any additional cleanup that isn't blocking. and the caller won't know the actual reason we are bailing so quickly.

File: src/main/java/org/cru/redegg/servlet/RedEggFilter.java [hunk 2]
```diff
@@ -52,6 +52,7 @@ private void doFilter(HttpServletRequest request, HttpServletResponse response,
         throws IOException, ServletException {
         RecordingResponse recordingResponse = new RecordingResponse(response);
         RecordingRequest recordingRequest = new RecordingRequest(request, errorLog, getRecorder());
+        getRecorder().startMonitoringRequestForTimeliness();
```
Comment (frett) [inline src/main/java/org/cru/redegg/servlet/RedEggFilter.java]: for this filter it doesn't appear that you ever stop monitoring the request

Comment (frett) [reply src/main/java/org/cru/redegg/servlet/RedEggFilter.java]: Or is it a combination between starting here and ending the monitoring within `RedEggServletListener`

Comment (mattdrees) [reply src/main/java/org/cru/redegg/servlet/RedEggFilter.java]: that's right.
It's nice to stop monitoring as late as possible, so we can potentially catch problems further down the filter stack.

Offhand, I can't remember why I didn't start monitoring in the servlet listener as well, but I believe there was some reason.

File: src/main/java/org/cru/redegg/recording/impl/DefaultStuckThreadMonitor.java (hunk 1 above)
Comment (mattdrees) [reply src/main/java/org/cru/redegg/recording/impl/DefaultStuckThreadMonitor.java]: Yeah, I don't know the best way to handle this case. It's not a likely case, so I didn't spend much time thinking about it.

I think you're right, though. And actually I did what you suggest in another place. I'll extract a helper from it.

Comment (mattdrees) [reply src/main/java/org/cru/redegg/recording/impl/DefaultStuckThreadMonitor.java]: Ok, fixed/squashed.
Also, I added a shutdownNow() call.

File: src/main/java/org/cru/redegg/servlet/RedEggFilter.java (hunk 2 above)
Comment (mattdrees) [reply src/main/java/org/cru/redegg/servlet/RedEggFilter.java]: I can't find a good reason.
Perhaps I was mis-thinking that this would let the entity be available in stuck-request reports.
Or maybe I was thinking I was going to allow some non-http details to be recorded by the app (which would be reported in stuck thread reports), in a custom filter or something; but I didn't implement that. 

I'm going to change this.

Comment (mattdrees) [reply src/main/java/org/cru/redegg/servlet/RedEggFilter.java]: done

**Comment by mattdrees** [comment]
I changed the link to an RFC 8288 link, as discussed in Slack.
Think I'm all done here, now.

**Comment by mattdrees** [comment]
I was wrong. I added two more commits. I think I'm done now, but I want to test this in give-ep locally first. I'll comment when that is successful.

**Comment by frett** [comment]
K, I'll take a look at those 2 commits later this afternoon

**Comment by mattdrees** [comment]
thanks!
